FROM 2345.com/centos:7
MAINTAINER sunzq@2345.com
RUN yum install -y vim 
RUN yum install -y java-1.8.0-openjdk.x86_64
RUN yum install -y net-tools
RUN yum install -y unzip
RUN yum install -y curl
RUN yum install -y tar
RUN yum install -y gzip
RUN yum install -y lrzsz
